### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by vochor** [KitchApp/KitchApp-Android#11]
When I click some Button in the main screen: "Lista de la Compra", "Despensa", "Recetario", "Estadisticas", "Localización" the application goes to the same scren "Despensa". And when I click any button in Despensa the app crash and It reports the message: "Unfortunately, KitchApp has stopped".

My device is: Samsung Galaxy Fame with Android 4.1.2

**Comment by irequena-dev** [comment]
I have the same problem.

My device is: Google Nexus 4 with Android 4.4.2
