### ISSUE TITLE
Login con Sqlite

### ISSUE THREAD

**Issue by vivianasandagorda** [KitchApp/KitchApp-Android#9]
Implementar el Login del usuario con la base de datos interna, de momento está funcionando con HashMap

**Comment by evillarroelcuadrado** [comment]
Ya está implementado, sustituí el HashMap que teníamos en un principio por la base de datos local (SQLite) y también implementé con base de datos local a la hora de registrarse poniendo también la restricción de que el correo introducido por el usuario sea tipo "example@dominio.com/es" y funciona!
